language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"
# command to install dependencies
install:
  - "pip install --upgrade pip"
# command to run tests
script: nosetests
notifications:
  - email: false