language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"
# command to install dependencies
install:
  - "pip install ./pip-6.0.8"
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests
notifications:
  - email: false